channels:
  - conda-forge
dependencies:
  - ase
  - atomap
  - dask==2021.3.1
  - distributed==2021.3.1
  - dask-labextension
  - hyperspy-base
  - hyperspy-gui-ipywidgets
  - ipympl
  - kikuchipy
  - lumispy
  - nglview
  - particlespy
  - python-graphviz
  - pystackreg
  - pyxem
  - scanning_drift_corr
  - scikit-learn
