channels:
  - conda-forge
dependencies:
  - ase
  - atomap
  - dask <2021.04.0
  - hyperspy-base
  - hyperspy-gui-ipywidgets
  - ipympl
  - kikuchipy
  - lumispy
  - nglview
  - particlespy
  - pystackreg
  - pyxem
  - scanning_drift_corr
  - scikit-learn

